# Server-Port der Demo-App
server.port=8080

# Vaadin: Pakete für das Routen-/Komponenten-Scanning (Komponente + App)
vaadin.allowed-packages=de.makno.xmlviewer.component,de.makno.xmlviewer.app,de.makno.xmlviewer.navigation

# Etwas ruhigeres Log beim Start
logging.level.org.atmosphere=warn
